cli_decoding:
    adblock: false
    adblock_aggressive: false
    rpz: false
    wildcard: false
cli_testing:
    autocontinue: true
    ci:
        active: false
        branch: master
        command: ''
        commit_message: PyFunceble - AutoSave
        distribution_branch: master
        end_command: ''
        end_commit_message: PyFunceble - Results
        max_exec_minutes: 15
    complements: false
    cooldown_time: 0.0
    days_between:
        db_clean: 28
        db_retest: 1
    db_type: csv
    display_mode:
        all: false
        colour: true
        dots: false
        execution_time: false
        less: true
        percentage: true
        quiet: false
        simple: false
    file_filter: ''
    file_generation:
        analytic: true
        hosts: true
        no_file: false
        plain: false
        unified_results: false
    hosts_ip: 0.0.0.0
    inactive_db: true
    local_network: false
    max_workers: null
    mining: false
    sorting_mode:
        hierarchical: false
        standard: true
    testing_mode:
        availability: true
        reputation: false
        syntax: false
    whois_db: true
debug:
    active: false
    level: info
dns:
    protocol: UDP
    server: null
http_codes:
    list:
        potentially_down:
        - 400
        - 402
        - 403
        - 404
        - 409
        - 410
        - 412
        - 414
        - 415
        - 416
        potentially_up:
        - 0
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 307
        - 403
        - 405
        - 406
        - 407
        - 408
        - 411
        - 413
        - 417
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        up:
        - 100
        - 101
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
    not_found_default: XXX
links:
    api_date_format: https://pyfunceble.funilrys.com/api/date-format
    api_no_referer: https://pyfunceble.funilrys.com/api/no-referer
    user_agents: https://raw.githubusercontent.com/PyFunceble/user_agents/master/user_agents.json
logs: true
lookup:
    dns: true
    http_status_code: true
    netinfo: true
    reputation: false
    special: true
    timeout: 5
    whois: true
multiprocess: false
multiprocess_merging_mode: end
no_http_codes: false
shadow_file: false
share_logs: false
store_whois_record: false
unified: false
user_agent:
    browser: chrome
    custom: null
    platform: linux
verify_ssl_certificate: false
