name: PyFunceble CI tests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 * * * *"

env:
  PYFUNCEBLE_AUTO_CONFIGURATION: "YES"
  GIT_NAME: "${{ secrets.GIT_BOT_NAME }}"
  GIT_EMAIL: "${{ secrets.GIT_BOT_EMAIL }}"

jobs:
  single:
    name: Run PyFunceble with a single domain
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9.1"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: "${{ secrets.BOT_REPO_PAT }}"

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install git+https://github.com/funilrys/PyFunceble.git@4.0.0-dev

      - name: Get PyFunceble version
        run: |
          PyFunceble --version
        env:
          PYFUNCEBLE_CONFIG_DIR: "${{ github.workspace }}/.pyfunceble"

      - name: Run PyFunceble
        run: |
          PyFunceble -a --logging-level critical -d github.com
        env:
          PYFUNCEBLE_CONFIG_DIR: "${{ github.workspace }}/.pyfunceble"

  file_and_push:
    name: Run PyFunceble against a file and push result to repository
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9.1"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: "${{ secrets.BOT_REPO_PAT }}"

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install git+https://github.com/funilrys/PyFunceble.git@4.0.0-dev

      - name: Get PyFunceble version
        run: |
          PyFunceble --version
        env:
          PYFUNCEBLE_CONFIG_DIR: "${{ github.workspace }}/.pyfunceble"

      - name: Run PyFunceble
        run: |
          PyFunceble -a --ci --logging-level critical -f test.list
        env:
          PYFUNCEBLE_CONFIG_DIR: "${{ github.workspace }}/.pyfunceble"
          GITHUB_TOKEN: "${{ secrets.BOT_REPO_PAT }}"
